### PR TITLE
Prepare POGOLib for distribution

### PR DESCRIPTION
**Pull request by Qonstrukt**
Hi, I saw issue #7 this week and decided I could give this a go because I want to integrate this in a Xamarin.iOS project, and that's impossible in it's current state, while with some changes it's easily doable.

I did the following to improve the distributability and compatibility with other platforms:
- Convert the project to a PCL with profile 78.
- Refactor the code to work asynchronous as in it's current state it freezes during session creation.
- Remove the dependency on log4net as platform support for it is pretty bad.

Unfortunately I'm tied to working with Xamarin Studio, and I can't seem to get HttpClient working in console apps on my Mac. So I updated the demo, but I'm not sure if it works.

Also, the formatting seems to be a little different from Visual Studio, and especially csproj and xml changes edit the tab width, and I can't seem to change this effectively from Studio.

If you find this useful and want me to fix the differences with Visual Studio I guess I could ring up an installation, but I'd like to hear your thoughts first!

(This implementation is tested on iOS, and it works great there! So thanks for this project, saves me a lot of time!)

### CODE REVIEW

**Comment by Qonstrukt** [comment]
Hmm, so it seems that MSBuild is a lot stricter on Windows than on Mac. So I might have to switch out the System.Device.Location.Portable package.

**Comment by AeonLucid** [comment]
I've merged a PR which should solve your System.Device.Location.Portable issue. I like your async changes but I haven't heard of "PCL with profile 78" before, I'll read into that. 

Can't really look deep into the other things as I don't have access to a pc until 8 August. :(

**Comment by Qonstrukt** [comment]
No problem, no rush 😄 
I'll rebase this on the latest changes. 

A portable class library (PCL) is mostly a regular library, but it doesn't have any access to platform specific assemblies (directly). And since your code was already really portable (platform independent), it wasn't much of a problem, just a matter of finding the right packages on NuGet.

In the coming months the [.NET Standard Library](https://docs.microsoft.com/en-us/dotnet/articles/standard/library) will compliment this further, but support on other platforms isn't that great yet, but that'll change in the fall.

**Comment by Qonstrukt** [comment]
It's a shame the Template functionality was added as is, because it uses the file system, and you can't do that from a portable library. I don't think I exactly understand what it does, but there's multiple ways to fix this.

What I'd normally do for a simple caching-like structure is use [Akavache](https://github.com/akavache/Akavache), so I'm gonna go ahead and use that. Mostly because I want to go further with my own project, but I can imagine this might be up for debate.

[Edit]
I actually think you want to move this out of the library and up to the application implementation. So I'll check if I can abstract it for now.

**Comment by Qonstrukt** [comment]
Ok, so I think I'll be done for now. 😉 

I've reverted back to S2Geometry 1.0.1 since the last PR, because it uses a NETStandard profile, and Xamarin Studio doesn't like that very much yet. I can't satisfy all dependencies when I use that version.

**Comment by AeonLucid** [comment]
@Qonstrukt Hey, it has been some time and lots of changes have been made since this PR.
I'd love to target multiple frameworks (iOS, Android, other .NET frameworks versions).

I already have NuGet packaging setup correctly for .NET 4.5 but wish to add the above too.
Could you help accomplish? I don't really have experience in targeting multiple frameworks in one project.

**Comment by AeonLucid** [comment]
https://github.com/AeonLucid/POGOLib/tree/pcl

**Comment by Nacorpio** [comment]
@AeonLucid Go to bed.

**Comment by fonix232** [comment]
No need to target multiple platforms - just make the target of the library Profile 78 or 259 (latter is preferred for its broader reach, and as POGOLib does not use WCF, it's fine).

**Comment by Qonstrukt** [comment]
I guess we can close this PR as it seems all the work has been done now. Would've been easier to just merge it though. 😉 

I wouldn't target profile 259 though, as I can't see why anyone would still want to use this in a Silverlight app. I honestly think profile 111 is the best choice as it targets all the relevant recent platforms, but there were some problems with the new NETStandard dependencies on NuGet which prevented me from choosing 111. Unfortunately that bug still isn't fixed: https://github.com/dotnet/corefx/issues/10445

**Comment by fonix232** [comment]
Well to be honest I just ported a good majority of the code (including Geocoordinateportable and GPSOAuth) to netstandard1.3 (1.0 through 1.2 is not going to work due to the System.Security.Cryptography libraries. Sure we could use some portable crypto for the GPSOAuth RSA and SHA stuff, but that's about it), and made a pull request.

RuntimeInformation is not necessary in my opinion - given the diversity of platforms supported by .Net Core (and .Net Standard), there's little performance increase in using xxHash64 (as most legal use cases will not be bots, but re-makes of the game for e.g. UWP, and a majority will be ARM-based with limited RAM bandwidth, even on 64-bit ARM platforms the speeds won't be higher using the 64 bit variant).

**Comment by AeonLucid** [comment]
https://github.com/AeonLucid/POGOLib/tree/proper-pcl

**Comment by Qonstrukt** [comment]
Well, I fetched the proper-pcl branch this afternoon, and I'm using it now. Besides the issues pointed out in PR #42, I have little problems with it, and I noticed you're using profile 111 right now, which seems fine to me. (Native HttpClient etc.)

I also noticed some packages included as sub modules, the same packages that depend on RuntimeInformation which are impossible to install currently, so I'm guessing you did this to circumvent that issue.

I would recommend looking into a service locator like Splat's (not necessarily Splat's of course) to ease the use of different IDataCache implementations and allow testing projects to more easily inject other variations.

**Comment by clairernovotny** [comment]
FWIW, you can use netstandard for any project type. Xamarin supports it too now, so there's really no reason to create a profile-based PCL anymore.

**Comment by AeonLucid** [comment]
This is a bit outdated now and we are now running on .NetStandard1.1. Closing this PR.

**Pull request closed without merging**
