### PR TITLE
Move to PCL - .Net Standard 1.3

### PR DESCRIPTION
**Pull request by fonix232**
A working update to the current master branch code to move it to PCL.

It's targeting .Net Standard 1.3 for now, mainly because the GPSOAuth code requires System.Security.Cryptography. This can be fixed by replacing it with PCLCrypto, however due to my limited experience with crypto in .Net (and general), I'm incapable of doing the transition in a timely manner.

Nonetheless this code base should work fine for now - targeting 1.0 after replacing the Crypto part should be relatively easy. Until then the library will be only compatible with:
- .Net 4.6
- UWP
- All Mono/Xamarin platforms
- .Net Core

Dependencies are limited as I moved both GPSOAuth (an async version with HttpClient) and the Geocoordinate code into the main library.

Things to do:
- [ ] Make most of the network calls async
- [ ] Extend compatibility to Windows 8.0/8.1
- [ ] Extend compatibility to Windows Phone 8.0/8.1

### CODE REVIEW

**Comment by zone117x** [comment]
Hey man check out the PCL branch on this repo. This work is already being done :)

**Comment by AeonLucid** [comment]
https://github.com/AeonLucid/POGOLib/tree/proper-pcl

**Comment by fonix232** [comment]
The PCL branch still targets the deprecated Profile system, while my pull request fully incorporates the now mainstream .Net Standard way of defining stuff.

It also uses Nuget 3.0 which makes it incompatible with VS2013 and prior.

The current PCL branch also duplicates code unnecessarily (Oren Novotny's S2Geometry is already netstandard1.0 compatbile, however it is not backwards compatible with Profile111/78/259).

However if you published your GPSOAuthSharp and pokemongo-encrypt-sharp packages as netstandard1.x Nuget packages, it would speed things up (and could get rid of the unnecessary git submodules).

**Comment by zone117x** [comment]
> The PCL branch still targets the deprecated Profile system, while my pull request fully incorporates the now mainstream .Net Standard way of defining stuff.

This is untrue. The profile system is still the default way of creating cross platform libraries, especially for use with Xamarin targets. 

.NET Standard is definitely not "mainstream" yet. The ConsoleDemo project cannot reference the .NET Standard project without upping the target framework to 4.6 - which is not an option for many projects that need to stick with 4.5.1 or lower. 

.NET Standard is still in preliminary phases. In fact, the `project.json` format is even being deprecated https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/

When .NET Standard is indeed "mainstream" then we can convert to it, but for now it is too early.

**Comment by fonix232** [comment]
The reason why the project had to be upped to 4.6 was because I had to use netstandard1.3 as target, as I used System.Security.Cryptography for GPSOAuth. If I were to follow your code and replace it with BouncyCastle Portable, it would work fine with netstandard1.0 and the Demo project could stay 4.5.

**Pull request closed without merging**
