### PR TITLE
Inventory Fix, Protos, Cleanup

### PR DESCRIPTION
**Pull request by Lizzaran**
- Fixed inventory - #15 
- Updated to latest protos
- Updated C5
- Removed Configuration.Debug as it was only used for the Log messages which should be handeld by the log4net config
- Removed GetFortsSortedByDistance
- Various changes from Lennix
- General cleanup

### CODE REVIEW

**Comment by AeonLucid** [comment]
Looks good, thanks for all the fixes. Currently on holiday so I am unable to fix stuff. Thank you!!

**Comment by Lennix** [comment]
Thanks for adding the credits Lizzaran... At least it merged now

**Comment by pingec** [comment]
Seems like inventory merging needs some polishing and null handling. Here is an example when an unchecked null sneaks in.

pogolibinventoryexception
pogolibinventorynulls

**Comment by Lennix** [comment]
@sodanakin Just fork the current master and re-add it yourself

**Comment by Lennix** [comment]
@pingec I don't know why he changed my implementation (https://github.com/Lennix/POGOLib/tree/Inventory), it's working great...

**Comment by Lizzaran** [comment]
@pingec 
Mhm. Perhaps: 
`InventoryItems.AddRange(delta.InventoryItems.Where(i => i != null));`
??

@Lennix 
Sorry, but as far as I can see, your implemented does nothing beside throwing null errors.
You never set the new field InventoryDelta but use it in the RPCClient.

**Comment by pingec** [comment]
@Lizzaran that seems to work for me, yes

**Comment by Lennix** [comment]
@Lizzaran You're right, I forgot to push a commit.

**Pull request merged**
