### PR TITLE
Make compilable on Mono

### PR DESCRIPTION
**Pull request by PoroCYon**
As always, Certified to Work on My Machine

### CODE REVIEW

**Comment by PoroCYon** [comment]
I'd fix the failing build, but the AppVeyor page seems to be loading endlessly when I open it...

**Comment by fonix232** [comment]
Just a suggestion - as you're using GeoCoordinatePortable, just move it to the System.Device.Location namespace, practically overriding the old classes (this in theory will have no ill effect, given it is 1:1 API compliant). That way there won't be need for those nasty compile-time checks.

**Comment by PoroCYon** [comment]
I know, but that would be a bit ugly imo.

**Comment by fonix232** [comment]
Not necessarily - this way you have to edit ALL files that use the namespace and classes. You could put it in the namespace, AND put the whole class definition into an `#if MONO` clause.

**Comment by PoroCYon** [comment]
The second isn't needed, because the files are only compiled when using XBuild (i.e. Mono), and non-stdlib things shouldn't be in `System`.

**Comment by Recio** [comment]
@PoroCYon I actually implemented your changes on the newest POGOLib update and can't seem to get my app to work.

Always crash when using Google Auth, did you use Google Auth or PTC ?
Cheers

**Comment by fonix232** [comment]
@PoroCYon sorry for the late reply. I understand your concerns in touching stuff within the System namespace, but here you're porting a native .Net feature to an unsupported platform. Moving it to a different namespace will only cause confusion, and on the long run, lots of problems and #IF-s.

**Pull request closed without merging**
